packer {
  required_plugins {
    virtualbox = {
      source  = "github.com/hashicorp/virtualbox"
      version = "~> 1"
    }
  }
}

source "virtualbox-iso" "autogenerated_1" {
  boot_command      = ["<esc><wait>", "<esc><wait>", "<enter><wait>", "/install/vmlinuz noapic ", "initrd=/install/initrd.gz ", "autoinstall ds=nocloud-net;s=http://{{ .HTTPIP }}:{{ .HTTPPort }}/ ", "<enter>"]
  disk_size         = 10000
  guest_os_type     = "Ubuntu_64"
  headless          = false
  http_directory    = "http"
  iso_checksum      = "sha256:443511f6bf12402c12503733059269a2e10dec602916c0a352c7f9343b6e1a63"
  iso_checksum_type = "sha256"
  iso_url           = "http://releases.ubuntu.com/20.04/ubuntu-20.04.2-live-server-amd64.iso"
  shutdown_command  = "echo 'packer' | sudo -S shutdown -P now"
  ssh_password      = "packer"
  ssh_username      = "packer"
  ssh_wait_timeout  = "20m"
  vboxmanage        = [["modifyvm", "{{ .Name }}", "--memory", "1024"], ["modifyvm", "{{ .Name }}", "--cpus", "1"]]
  vm_name           = "ubuntu-packer"
}

build {
  sources = ["source.virtualbox-iso.autogenerated_1"]

  provisioner "shell" {
    inline = ["echo 'packer ALL=(ALL) NOPASSWD:ALL' >> /etc/sudoers", "apt-get update", "apt-get upgrade -y"]
  }

}
