Debian = "bento/debian-12"
Ubuntu = "bento/ubuntu-22.04"

Vagrant.configure("2") do |config|
	(1..3).each do |i|
		config.vm.define "debian-#{i}" do |node|
			node.vm.box = Debian
			node.vm.hostname = "amin-#{i}"
			node.vm.provider "virtualbox" do |v|
				v.name = "my_vm_#{i}"
				v.memory = 1024 
				v.cpus = 1
			end
			node.vm.provision :shell, path: "bootstrap.sh"
		end
	end
end

Vagrant.configure("2") do |config|
	config.vm.box = Ubuntu
	config.vm.hostname = "amin-ubuntu"
	config.vm.provider "virtualbox" do |v|
		v.name = "root"
		v.memory = 1024
		v.cpus = 1
	end
	config.vm.provision :shell, path: "bootstrap.sh"
end
